apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: update-member-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: update-member-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/broker_member_member
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /onboarding/broker_member_member
