include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-SH8c

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-us-broker-mmbr-fn-29ff7804-45e2-4d5b-9bea-8e5efe4a4516
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-SH8c
  environment:
    name: onb-us-broker-mmbr-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T13:08:12Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-us-broker-mmbr-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-us-broker-mmbr-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-us-broker-mmbr-fn-29ff7804-45e2-4d5b-9bea-8e5efe4a4516
      namespace: default
  requestsPerPod: 10000
  resources: {}
